### ISSUE TITLE
Need to find a way to process Hex into readable text.

### ISSUE THREAD

**Issue by dmahony** [dmahony/Lora-Chat-Device#2]
The output when receiving a message is like this:
{'cad_detected': 0, 'fhss_change_ch': 0, 'cad_done': 0, 'crc_error': 0, 'tx_done': 0, 'valid_header': 1, 'rx_timeout': 0, 'rx_done': 1}
['0x48', '0x65', '0x6c', '0x6c', '0x6f', '0x20', '0x57', '0x6f', '0x72', '0x6c', '0x64' ,'0x21']

Ideally it would be output like this:

Hello World!

**Comment by mdxe** [comment]
Please take a look at this commit, hopefully that should convert the hex values list to a text string: https://github.com/mdxe/pySX127x/commit/3875af8ea278fc8409b04948f2dadf98065d4352
