### ISSUE TITLE
Trying to merge it_sends.py into it_receives.py

### ISSUE THREAD

**Issue by dmahony** [dmahony/Lora-Chat-Device#3]
Please check the new file combine_rx_tx.py to see my attempt.
I get this error when I run it:

```
Enter a message >>
ttt
Traceback (most recent call last):
  File "combine.py", line 118, in <module>
    lora.send()
  File "combine.py", line 86, in send
    handle_input(input)
NameError: global name 'handle_input' is not defined
```

**Comment by dmahony** [comment]
@mdxe Do you know why it is telling me that handle_input is not defined?

**Comment by mdxe** [comment]
Merged pull-request https://github.com/dmahony/Lora-Chat-Device/pull/6 should have fixed this issue
