### ISSUE TITLE
Trying to find a way to autorun my python scripts upon login (only for specific user)

### ISSUE THREAD

**Issue by dmahony** [dmahony/Lora-Chat-Device#4]
If anyone knows, please get in touch!

**Comment by mdxe** [comment]
Which OS?

**Comment by dmahony** [comment]
Sorry, I should have clarified, for Linux on the Raspberry Pi. I sort of
got it working but it runs the script for every user. I need it to run just
for a single user. The lora chat app should run as it's own user so I can
keep it locked down.

**Comment by mdxe** [comment]
You could add a line to ~/.bashrc that will run the script upon login for the current user (but if you open multiple shells, it would run it multiple times)

**Comment by dmahony** [comment]
I have the command in /etc/bash.bashrc but I need to find where to put it for a specific user.

**Comment by mdxe** [comment]
~/.bashrc means /home/username/.bashrc and it will run only for username

**Comment by dmahony** [comment]
Excellent! thanks for that.
